### ISSUE TITLE
训练报错了

### ISSUE THREAD

**Issue by linjeno** [chasezcz/LogAnomalyIdentify#1]
你好，运行train.py的时候报错
FileNotFoundError: [Errno 2] No such file or directory: './data/input/800_30/train'

我没有找到这个文件，请问是在哪里得到的

**Comment by chasezcz** [comment]
这是训练文件，隐私问题无法上传；代码仅提供思路，不保证稳定运行

**Comment by linjeno** [comment]
我想学习您的数据预处理方法，能否方便发个样本呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chengze ***@***.***&gt;; 
发送时间: 2023年6月13日(星期二) 下午5:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [chasezcz/LogAnomalyIdentify] 训练报错了 (Issue #1)





 
这是训练文件，隐私问题无法上传；代码仅提供思路，不保证稳定运行

**Comment by chasezcz** [comment]
不行啊同学，一是敏感数据确实无法外传；二是我已经离开做这份工作的组织了，手里没有数据的；你使用你的数据就可以了啊；

再者，lstm 的方式目前看来，方法存在问题，从数据特征角度来说，仅适用于当时的特殊场景，而不是一个泛用的模型；

本实验的思路一定程度上借鉴了 google 的 deeplog，且 github 上有大佬已经做了集成，https://github.com/donglee-afar/logdeep
